name: changesets
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  renovate:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'dependencies') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add Changeset
        uses: generates/changeset-action@v3.0.0
      - name: Commit Changes
        uses: generates/commit-action@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
